/**
 * Swagger Camel Passthru
 * This is a Camel passthru API to Unimart App server. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rdelacruz@stratpoint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerCamelPassthru);
  }
}(this, function(expect, SwaggerCamelPassthru) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerCamelPassthru.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('apiDelete', function() {
      it('should call apiDelete successfully', function(done) {
        //uncomment below and update the code to test apiDelete
        //instance.apiDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiGet', function() {
      it('should call apiGet successfully', function(done) {
        //uncomment below and update the code to test apiGet
        //instance.apiGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPost', function() {
      it('should call apiPost successfully', function(done) {
        //uncomment below and update the code to test apiPost
        //instance.apiPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPut', function() {
      it('should call apiPut successfully', function(done) {
        //uncomment below and update the code to test apiPut
        //instance.apiPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
